### ISSUE TITLE
Casting spells

### ISSUE THREAD

**Issue by EdwinRou** [Lucas1774/League-of-Legends-Swarm-Controller-Adapter#1]
Hi,
How do you cast spells ? I tested quickly and L1/R1 are not working for me (doing nothing or moving the mouse cursor on the screen).

Thx for the repo though !

**Comment by Lucas1774** [comment]
Hi,

The default configuration is probably not right for you because it is for me and my controller is very weird.

You need to map button names to button ids in the `config.json` file at the root of the repo.

Use windows game controller software to figure out the ids of your specific controller
![image](https://github.com/user-attachments/assets/4c9c4ec2-2c64-4d08-a7b3-343a80839ab8)

If this doesn't work please come back to me, cause I'm curious about why. I close this though.
